Dark and Light Mode Fixed
metabrainz/listenbrainz-android pull request #116
Opened 2023-03-27 18:17 UTC by SB2318

### Issue Link: https://tickets.metabrainz.org/browse/MOBILE-132

### What Happening?
There was a little problem applying the theme in the app.
Let me take one situation, what I have also tried to detect through this video.

Suppose, your application is in light mode, And you change the theme to dark, everything is fine, and the dark mode has perfectly applied to your app.
Again, you come back to the settings and change it into light mode, but the theme is not applying as expected. But when we removed the application from **back-stack**, and again **relaunch** everything is fine.

Please go through this Video:

https://user-images.githubusercontent.com/87614560/228027513-8d0eda08-0f25-4c0c-9bed-bd6bd61daf78.mp4

### My Approach:

Actually, there is no problem with the previous code, from my knowledge. It is happening because somehow the application is not receiving any update about the UI Mode as soon as it updating. Like, somehow we have to broadcast all the components that yes something is happening.

Then I have also gone through some of the Play Store applications, where they apply something like this. So, after also seeing their approach in this type of case, I am just restarting the application when the UI mode change is happening.

It works.

### Result:

https://user-images.githubusercontent.com/87614560/228029631-25f6e9ba-1e4a-48db-8f5b-c4ec591d6527.mp4

(This branch is updated with the current main branch)

Fixes #107

2023-03-27 19:34 UTC, 07jasjeet commented
Hitting back should return us to the original instance of `DashboardActivity`. Correct me if I'm wrong?

2023-03-27 19:37 UTC, SB2318 commented
> Hitting back should return us to the original instance of `DashboardActivity` which is bugged. Correct me if I'm wrong?

Yes you are right 😅, will try to solve it. give me some time

2023-03-27 19:40 UTC, akshaaatt requested changes

2023-03-27 19:44 UTC, SB2318 commented on app/src/main/java/org/listenbrainz/android/ui/screens/settings/SettingsActivity.kt
> +                        startActivity(Intent(this@SettingsActivity,DashboardActivity::class.java))
Get it. Thank You, will try

2023-03-30 19:00 UTC, closed without merging

2023-03-30 22:34 UTC, SB2318 commented
> As I can see, you have decided to take this problem into a separate PR, hence closing this one. Also @SB2318 , why are you opening separate PRs for the same problem? You can commit new updates on the same branch and those changes will automatically be reflected in the PR.

okay