Fix: Declare NewsBrainzActivity in androidManifest
metabrainz/listenbrainz-android pull request #160
Opened 2023-05-28 15:50 UTC by prabalsingh24

Clicking the News button in the main screen does not open the News activity as it's not defined in the AndroidManifest

2023-05-28 15:55 UTC, prabalsingh24 commented
@akshaaatt idk why but I can't seem to add you a reviewer. Tagging you :)

2023-05-29 05:08 UTC, akshaaatt requested changes
Thanks a lot for bringing this up! 💯 
I removed it by mistake in my previous commits while removing the Settings activity.

2023-05-29 05:08 UTC, akshaaatt commented on app/src/main/AndroidManifest.xml
> +            <meta-data
This is not a shared library or anything so we don't need this tag here. Please remove it.

2023-05-29 05:08 UTC, akshaaatt commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"
We don't actually need to specify this until and unless an intent filter is added to the activity.

2023-05-29 05:08 UTC, akshaaatt commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/AppTheme">
The default theme for the app is this, hence even if we don't duplicate it here, it will pick the same theme.

2023-05-29 16:05 UTC, akshaaatt commented
@prabalsingh24 I was in a hurry to make a beta release of the app, hence pushed the fix for it. Thanks a lot for bringing this up though! 💯

2023-05-29 16:05 UTC, merged