Fix: FollowButton and compatibilty color scheme in light theme
metabrainz/listenbrainz-android pull request #506
Opened 2024-12-15 18:25 UTC by Shreyassp002

This PR addresses issues with the **Follow Button** and **Similar Artists** section for the light theme. The following changes have been made:
- Corrected the styling of the **Follow Button** to match the light theme.
- Fixed text color inconsistencies in the **Compatibility** section for better visual consistency.

## Screenshots   
### Issue:
![issue 1](https://github.com/user-attachments/assets/ed50e85f-3d09-4103-8639-3953071eb9ee)

![issue 2](https://github.com/user-attachments/assets/a20b3c4b-0d07-44d1-af52-3880ca850168)

![issue 3](https://github.com/user-attachments/assets/d6ca6f80-649a-42c1-8bc7-1aaf57761c24)

### Fixes:
![Screenshot_2024-12-15-23-36-40-908_org listenbrainz android debug](https://github.com/user-attachments/assets/049dd2f2-3c59-441d-9fa7-6f7fde42f5eb)

![Screenshot_2024-12-15-23-37-03-659_org listenbrainz android debug](https://github.com/user-attachments/assets/21f84720-abbb-489f-acda-8e41242ebce9)

![Screenshot_2024-12-15-23-37-54-849_org listenbrainz android debug](https://github.com/user-attachments/assets/4a4fb75d-d80e-4174-b934-2dd6436e6450)

Let me know if there are any changes needed to the color scheme or any other adjustments!

2024-12-23 13:24 UTC, 07jasjeet commented
Hi, thanks for the PR. We would like to keep the follow button same throughout the app, if you could replace the button with existing component entirely, it would be really great!

2024-12-23 15:45 UTC, Shreyassp002 commented
Hi @07jasjeet ,

Thank you for the feedback! Just to ensure consistency:

1. Could you confirm which existing button component you'd like me to replace the Follow button with? If possible, could you point me to the file or component name where it's implemented?

2. Regarding the state management updates I made for the Follow button across the ListenScreen and BaseProfileScreen, should I revert those changes as well, or should I adapt them to work with the existing component?

2024-12-24 04:38 UTC, 07jasjeet commented
1. @Shreyassp002 [this](https://github.com/metabrainz/listenbrainz-android/blob/main/app/src/main/java/org/listenbrainz/android/ui/components/FollowButton.kt) is the component I'm talking about. 
2. State management changes look good, no need to revert.

2024-12-24 12:33 UTC, Shreyassp002 commented
Hi @07jasjeet ,

I’ve updated the ListensScreen to use the requested component. The BaseProfileScreen already had the correct component in place, so no changes were needed there.

![photo_2024-12-24_17-52-27](https://github.com/user-attachments/assets/27ac4fe8-7e42-44b0-9237-1e787b00a16e)
![photo_2024-12-24_17-52-31](https://github.com/user-attachments/assets/eccc7883-1039-4548-b9ee-10f5b4bd7af2)


Please let me know if there is anything else that needs attention or further adjustments.

2024-12-27 10:57 UTC, 07jasjeet requested changes
Last bit changes

2024-12-27 10:57 UTC, 07jasjeet commented on app/src/main/java/org/listenbrainz/android/ui/screens/profile/listens/ListensScreen.kt
> +                    followedStateTextColor = ListenBrainzTheme.colorScheme.text,
```suggestion
                    followedStateTextColor = ListenBrainzTheme.colorScheme.lbSignature,
```

2024-12-27 10:58 UTC, 07jasjeet approved these changes
LGTM, Thanks for fixing this UI issue!

2024-12-27 10:58 UTC, merged