MOBILE-212: Highlight current playing song in song list
metabrainz/listenbrainz-android pull request #518
Opened 2024-12-28 18:28 UTC by Shreyassp002

This feature highlights the title of the currently playing song in the song list, making it easier for users to identify the active track.

**Changes:**

- Added a visual highlight to the title of the song currently playing in the list.
- Added logic to match the `currentlyPlayingTitle` with the title passed to the `BrainzPlayerListenCard` composable. If they match, the title color is set to `R.color.bp_color_primary`; otherwise, it uses the default text color from the theme.
- Also made some formatting fixes for better code readability

**Screenshots:**
<p align="center">
  <img src="https://github.com/user-attachments/assets/8de633ae-80be-4f9a-b638-c9b4c761ce36" alt="Screenshot 1" width="45%">
  <img src="https://github.com/user-attachments/assets/ce7165a0-6ede-4958-9762-58413e59ceb8" alt="Screenshot 2" width="45%">
</p>

**Issue Link:** [MOBILE-212](https://tickets.metabrainz.org/projects/MOBILE/issues/MOBILE-212)

This is the current implementation of feature. I’d love to hear your feedback or suggestions for improvement.

2024-12-29 13:14 UTC, Shreyassp002 commented
**Changed highlight color**

**Screenshots:**
<p align="center">
  <img src="https://github.com/user-attachments/assets/8d7ebc7b-c7c7-4894-b6b4-a80d5c22c65a" alt="Screenshot 1" width="45%">
  <img src="https://github.com/user-attachments/assets/65e4e3dd-8690-4a40-8fe7-93ec816fa469" alt="Screenshot 2" width="45%">
</p>

Let me know if any changes are required.

2024-12-29 15:01 UTC, Shreyassp002 commented
Added animated Play/Pause Icon transition in `BrainzPlayerListenCard`

- Updated the `PlayButton` composable to use `AnimatedContent` for animating the icon transition.
- Added fade-in and fade-out effects to the play/pause icon transition.
- Ensured the play/pause icon synchronizes correctly with the song's playing state.

**Screenshot:**

<img src="https://github.com/user-attachments/assets/556c71e8-4e2e-479b-9183-7bb7bc45c7e2" width="400" alt="Screenshot of the app">

2025-01-04 06:40 UTC, 07jasjeet requested changes

2025-01-04 06:40 UTC, 07jasjeet commented on app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
> +            brainzPlayerServiceConnection.currentPlayingSong.collectLatest { song ->
no need to collect the flow and emit to another flow.
```kotlin
val currentlyPlayingTitle = brainzPlayerServiceConnection.currentPlayingSong.map { it.title }
```

Also, rather than just flowing the title here, can we do `brainzPlayerServiceConnection.currentPlayingSong` only and use title wherever needed.

2025-01-04 06:41 UTC, 07jasjeet commented on app/src/main/java/org/listenbrainz/android/ui/components/BrainzPlayerListenCard.kt
> +    val titleColor = if (currentlyPlayingTitle == title) {
Have you tried using some other form of ID like `mediaID` of a song?

2025-01-04 06:46 UTC, 07jasjeet requested changes

2025-01-04 06:46 UTC, 07jasjeet commented on app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
> +        _currentlyPlayingTitle.value = mediaItem.title
no need to emit here, service connection should automatically update the above flow. If not, it would be a bug for BP Service connection that would need to be resolved.

2025-01-04 06:46 UTC, 07jasjeet commented on app/src/main/java/org/listenbrainz/android/ui/components/BrainzPlayerListenCard.kt
> +    val titleColor = if (currentlyPlayingTitle == title) {
Have you tried using some ID of sorts like `mediaID` of a song? That would be a better candidate for this kind of use case.

2025-01-04 06:46 UTC, 07jasjeet commented on app/src/main/java/org/listenbrainz/android/ui/components/BrainzPlayerListenCard.kt
> +        Color(0xFFB94FE5)
Use `ListenBrainzTheme.colorScheme.signatureInverse` maybe or is it not legible enough?

2025-01-06 11:56 UTC, Shreyassp002 commented on app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
> +            brainzPlayerServiceConnection.currentPlayingSong.collectLatest { song ->
Yeah, that’s better. 
Removing the redundant flow.

2025-01-06 12:06 UTC, Shreyassp002 commented on app/src/main/java/org/listenbrainz/android/ui/components/BrainzPlayerListenCard.kt
> +    val titleColor = if (currentlyPlayingTitle == title) {
Yes, I tried to match the currentlyPlayingSong.id with the mediaId passed to the BrainzPlayerListenCard from SongsOverviewScreen, but that didn't work out.

2025-01-06 12:26 UTC, Shreyassp002 commented on app/src/main/java/org/listenbrainz/android/ui/components/BrainzPlayerListenCard.kt
> +        Color(0xFFB94FE5)
If I’m not wrong, `lbSignatureInverse` uses `lb_orange`, but Aerozol asked for a combination of blue and violet. Please suggest any combination or shade you’d like.

2025-01-08 10:29 UTC, Shreyassp002 commented on app/src/main/java/org/listenbrainz/android/ui/components/BrainzPlayerListenCard.kt
> +    val titleColor = if (currentlyPlayingTitle == title) {
wait I figured out a way to use `mediaId` instead of the Title

2025-01-11 14:40 UTC, 07jasjeet commented
Hey @Shreyassp002, I tried this on my device and the song is only highlighted on songs screen inside brainzplayer. Implementing this all over the app would be blow out the scope of this PR. Can we make this work just inside brainzplayer tab?

Here's the following that needs to done inside Brainzplayer tab: 
1. BP Dropdown on every screen in BP tab.
2. Dynamic play button on every screen in BP tab.
3. Highlight the listen card via shading the background with `BrainzPlayerViewModel.playerBackgroundColor` created by @GautamCoder4019k
4. Highlight currently playing song on every screen in BP tab.

This feels like a huge task, we can split these into 3 PRs:
PR 1: Point 1
PR 2: Point 2
PR 3: Point 3 and 4

As for this PR, You can use this PR as a base branch for your other 3 PRs and we can close this one, or we you can complete any one of the task in this PR itself.

2025-01-12 09:43 UTC, Shreyassp002 commented
Hey @07jasjeet,  
Thank you for the detailed feedback! I have a couple of questions before proceeding:

1. Regarding point 1, "BP Dropdown on every screen in BP tab," could you clarify exactly what this means? Are you referring to the song selection dropdown or something else?  

2. Should I remove the play button completely from `BrainzPlayerListenCard`, or should it remain as it was before?  

3. I understand your concern about scope creep in this PR. I’ll split the tasks as suggested:  
   - I can handle point 2 (removing the dynamic play button and playing the song when the `BrainzPlayerListenCard` is clicked) in this PR.  
   - Then, I’ll create two more PRs for points 1, 3, and 4 accordingly.

2025-01-21 16:43 UTC, 07jasjeet commented
> Hey @07jasjeet,  
> Thank you for the detailed feedback! I have a couple of questions before proceeding:
> 
> 1. Regarding point 1, "BP Dropdown on every screen in BP tab," could you clarify exactly what this means? Are you referring to the song selection dropdown or something else?  
> 
> 2. Should I remove the play button completely from `BrainzPlayerListenCard`, or should it remain as it was before?  
> 
> 3. I understand your concern about scope creep in this PR. I’ll split the tasks as suggested:  
>    - I can handle point 2 (removing the dynamic play button and playing the song when the `BrainzPlayerListenCard` is clicked) in this PR.  
>    - Then, I’ll create two more PRs for points 1, 3, and 4 accordingly.  
> 

1. Currently, BP dropdown is not implemented on the albums tab and songs tab. For the songs tab, the implementation should be as recents tab, i.e., normal BP dropdown. As for albums, the page is messed up itself, and songs are displayed as albums. Let's remove the dropdown from every item in the tab.

2025-01-24 15:00 UTC, Shreyassp002 commented
HI @07jasjeet,
Point 2 has been addressed in this PR. The dynamic play button has been removed, and the song now plays directly when the card is clicked. Let me know if there are any further changes or refinements needed.

2025-01-26 14:24 UTC, 07jasjeet approved these changes

2025-01-26 14:26 UTC, 07jasjeet commented
Hi @Shreyassp002, I made some necessary changes surrounding dropdowns + code usages and updated ui for how a song is played, have a look when you can :)

2025-01-26 14:26 UTC, merged

2025-01-26 15:24 UTC, 07jasjeet commented
Thanks for the contribution @Shreyassp002!