Add : Profile screen converted to Composable.
metabrainz/listenbrainz-android pull request #78
Opened 2023-03-02 19:27 UTC by Vishvajeet590

2023-03-03 16:02 UTC, akshaaatt requested changes

2023-03-03 16:02 UTC, akshaaatt commented on app/src/main/java/org/listenbrainz/android/ui/screens/login/LoginScreen.kt
> +                    + "&scope=profile%20collection%20tag%20rating"
Let's remove these scopes now? We needed these in the MB android app before but don't see a need here.

2023-03-04 10:05 UTC, 07jasjeet commented
Please check out what I have done in #77 with listens activity (or BrainzPlayer activity) to get an idea what I meant and do changes as you understand. After the changes, remove the intent to start profile activity from Bottom Nav Bar, which means, the profile activity won't start when you click the profile option in bottom nav bar. I will fix it when I merge your work with mine in #77

2023-03-10 13:33 UTC, akshaaatt commented
We have to revamp the profile page entirely and populate things to it, so the effort of this PR would not be of much use if merged. Hence, closing it.

https://www.figma.com/file/tFLTQiq7QlA1oGRTJVtXml/ListenBrainz?node-id=206%3A9&t=FGkDXizks0pDLQtM-1 would be the desired design for the profile page.

2023-03-10 13:33 UTC, closed without merging